# This file is intentionally minimal to override the default engine settings.
# All other settings will use the SearXNG defaults.

server:
  # We bind to all interfaces so the service is accessible from other containers.
  bind_address: "0.0.0.0"
  # The default port for SearXNG is 8080.
  port: 8080

# By default, many useful engines are disabled. This configuration enables
# a curated list of reliable search engines for fact-checking.
engines:
  - name: google
    engine: google
    shortcut: go
    categories: [general, web]
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    categories: [general, web]
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: [general, web]
    disabled: false
    
  - name: brave
    engine: brave
    shortcut: br
    categories: [general, web]
    disabled: false

  - name: qwant
    engine: qwant
    shortcut: qw
    categories: [general, web]
    disabled: false
    
  - name: bing news
    engine: bing_news
    shortcut: bin
    categories: [news]
    disabled: false
    
  - name: google news
    engine: google_news
    shortcut: gon
    categories: [news]
    disabled: false
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox"]
    categories: [general]
    disabled: false

  - name: yandex
    engine: yandex
    shortcut: ya
    categories: [general, web]
    disabled: false
    
  - name: swisscows
    engine: swisscows
    shortcut: sc
    categories: [general, web]
    disabled: false
