"""Initial migration

from __future__ import annotations

from typing import Optional
Revision ID: a749f8c0e1c6
Revises:
Create Date: 2025-07-10 00:28:28.091644

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a749f8c0e1c6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
