"""Initial migration

Revision ID: a749f8c0e1c6
Revises:
Create Date: 2025-07-10 00:28:28.091644

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a749f8c0e1c6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nickname', sa.String(length=255), nullable=False),
        sa.Column('true_count', sa.Integer(), nullable=True, default=0),
        sa.Column('partially_true_count', sa.Integer(), nullable=True, default=0),
        sa.Column('false_count', sa.Integer(), nullable=True, default=0),
        sa.Column('ironic_count', sa.Integer(), nullable=True, default=0),
        sa.Column('total_posts_checked', sa.Integer(), nullable=True, default=0),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_checked_date', sa.DateTime(), nullable=True),
        sa.Column('warning_issued', sa.Boolean(), nullable=True, default=False),
        sa.Column('notification_issued', sa.Boolean(), nullable=True, default=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)

    # Create verification_results table
    op.create_table(
        'verification_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_nickname', sa.String(length=255), nullable=False),
        sa.Column('image_hash', sa.String(length=64), nullable=True),
        sa.Column('extracted_text', sa.Text(), nullable=True),
        sa.Column('user_prompt', sa.Text(), nullable=True),
        sa.Column('primary_topic', sa.String(length=100), nullable=True),
        sa.Column('identified_claims', sa.Text(), nullable=True),
        sa.Column('verdict', sa.Text(), nullable=True),
        sa.Column('justification', sa.Text(), nullable=True),
        sa.Column('confidence_score', sa.Integer(), nullable=True),
        sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
        sa.Column('vision_model_used', sa.String(length=100), nullable=True),
        sa.Column('reasoning_model_used', sa.String(length=100), nullable=True),
        sa.Column('tools_used', sa.Text(), nullable=True),
        sa.Column('reputation_data', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_id'), 'verification_results', ['id'], unique=False)
    op.create_index(op.f('ix_verification_results_user_nickname'), 'verification_results', ['user_nickname'], unique=False)
    op.create_index(op.f('ix_verification_results_image_hash'), 'verification_results', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_image_hash'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_user_nickname'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_id'), table_name='verification_results')
    op.drop_table('verification_results')

    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
