"""Add vision and reasoning models to verification result

Revision ID: ee311854afa1
Revises: a749f8c0e1c6
Create Date: 2025-07-15 21:32:55.890279

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee311854afa1"
down_revision: str | None = "a749f8c0e1c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes needed - vision_model_used and reasoning_model_used 
    # are already created in the initial migration
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes needed - this migration is now a no-op
    pass
    # ### end Alembic commands ###
