"""Add vision and reasoning models to verification result

Revision ID: ee311854afa1
Revises: a749f8c0e1c6
Create Date: 2025-07-15 21:32:55.890279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee311854afa1'
down_revision: Union[str, None] = 'a749f8c0e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_results', sa.Column('vision_model_used', sa.String(length=100), nullable=True))
    op.add_column('verification_results', sa.Column('reasoning_model_used', sa.String(length=100), nullable=True))
    op.drop_column('verification_results', 'model_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_results', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('verification_results', 'reasoning_model_used')
    op.drop_column('verification_results', 'vision_model_used')
    # ### end Alembic commands ###
